<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-OLTTCV0" name="com.hybrid.tests.NewTOURSTest" tests="1" failures="1" timestamp="09 Mar 2018 17:16:34 GMT" time="0.020" errors="0">
  <testcase name="NewTOURSValidation" time="0.020" classname="com.hybrid.tests.NewTOURSTest">
    <failure type="java.lang.AssertionError" message="expected [Welcome: iii] but found [Welcome: Mercury Tours]">
      <![CDATA[java.lang.AssertionError: expected [Welcome: iii] but found [Welcome: Mercury Tours]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.hybrid.tests.NewTOURSTest.NewTOURSValidation(NewTOURSTest.java:27)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </failure>
  </testcase> <!-- NewTOURSValidation -->
</testsuite> <!-- com.hybrid.tests.NewTOURSTest -->
